version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rift-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  rift:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rift-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/auth_db?sslmode=disable
      JWT_SECRET: dasdasdwefafdsaefafdsaf
      CHAT_WORKERS_SOCKETS: 200
    ports:
      - "8080:8080"

volumes:
  postgres_data:
